# Generated by Django 3.2.3 on 2021-07-12 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20210712_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestticket',
            name='approval_from',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approval_from', to='db.user'),
            preserve_default=False,
        ),
    ]
